### ISSUE TITLE
How to run the examples 

### ISSUE THREAD

**Issue by beshoo** [Rhymen/go-whatsapp#256]
First of all, I am not a GO developer, but I can learn since I am PHP developer

Now what I did,
1- I installed GO on my CentOs box
2- go get github.com/Rhymen/go-whatsapp
3- git@github.com:Rhymen/go-whatsapp.git
4- open the example folder ./login
5- go build
I got nothing / No error message. but ./login created
6- when I run ./login i got this error :

./login
```
panic: couldn't dial whatsapp web websocket: dial tcp: i/o timeout

goroutine 1 [running]:
main.main()
        /download/gowhatsap/go-whatsapp-master/examples/login/main.go:14 +0x285
[RANK]root:[/download/gowhatsap/go-whatsapp-master/examples/login]./login
panic: couldn't dial whatsapp web websocket: dial tcp: i/o timeout

goroutine 1 [running]:
main.main()
        /download/gowhatsap/go-whatsapp-master/examples/login/main.go:14 +0x285

```
 
Now i test the other foldesr:
```
[RANK]root:[/download/gowhatsap/go-whatsapp-master/examples/echo]go build
go: downloading github.com/Baozisoftware/qrcode-terminal-go v0.0.0-20170407111555-c0650d8dff0f
go: downloading github.com/gorilla/websocket v1.4.0
go: downloading github.com/pkg/errors v0.8.1
go: downloading github.com/golang/protobuf v1.3.0
go: downloading golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2
go: extracting github.com/pkg/errors v0.8.1
go: extracting github.com/gorilla/websocket v1.4.0
go: extracting github.com/Baozisoftware/qrcode-terminal-go v0.0.0-20170407111555-c0650d8dff0f
go: downloading github.com/mattn/go-colorable v0.1.1
go: downloading github.com/skip2/go-qrcode v0.0.0-20190110000554-dc11ecdae0a9
go: extracting github.com/mattn/go-colorable v0.1.1
go: extracting github.com/skip2/go-qrcode v0.0.0-20190110000554-dc11ecdae0a9
go: downloading github.com/mattn/go-isatty v0.0.5
go: extracting github.com/mattn/go-isatty v0.0.5
go: downloading golang.org/x/sys v0.0.0-20190222072716-a9d3bda3a223
go: extracting github.com/golang/protobuf v1.3.0
go: extracting golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2
go: extracting golang.org/x/sys v0.0.0-20190222072716-a9d3bda3a223
go: finding github.com/Baozisoftware/qrcode-terminal-go v0.0.0-20170407111555-c0650d8dff0f
go: finding github.com/mattn/go-colorable v0.1.1
go: finding github.com/skip2/go-qrcode v0.0.0-20190110000554-dc11ecdae0a9
go: finding github.com/mattn/go-isatty v0.0.5
go: finding golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2
go: finding github.com/gorilla/websocket v1.4.0
go: finding github.com/pkg/errors v0.8.1
go: finding github.com/golang/protobuf v1.3.0
go: finding golang.org/x/sys v0.0.0-20190222072716-a9d3bda3a223
# github.com/Rhymen/go-whatsapp/examples/echo
./main.go:37:9: assignment mismatch: 1 variable but wh.wac.Send returns 2 values

```

```
[RANK]root:[/download/gowhatsap/go-whatsapp-master/examples/chatHistory]go build
[RANK]root:[/download/gowhatsap/go-whatsapp-master/examples/chatHistory]ll
total 11292
-rwxr-xr-x 1 root root 11545722 Dec  2 15:44 echo
-rw-r--r-- 1 root root      240 Dec  2 15:44 go.mod
-rw-r--r-- 1 root root     2765 Dec  2 15:44 go.sum
-rw-r--r-- 1 root root     1983 Nov  8 15:32 history.go
-rw-r--r-- 1 root root     3426 Nov  8 15:32 main.go
[RANK]root:[/download/gowhatsap/go-whatsapp-master/examples/chatHistory]./echo
2019/12/02 15:44:42 error creating connection: couldn't dial whatsapp web websocket: dial tcp: i/o timeout
[RANK]root:[/download/gowhatsap/go-whatsapp-master/examples/chatHistory]

```

```
[RANK]root:[/download/gowhatsap/go-whatsapp-master/examples/checkNewVersion]./checkNewVersion
panic: couldn't dial whatsapp web websocket: dial tcp: i/o timeout

goroutine 1 [running]:
main.main()
        /download/gowhatsap/go-whatsapp-master/examples/checkNewVersion/main.go:33 +0x658
[RANK]root:[/download/gowhatsap/go-whatsapp-master/examples/checkNewVersion]

```

What I am missing here?

**Comment by beshoo** [comment]
I can open https://web.whatsapp.com in my lynix browser! 
So what do you think is the problem!

**Comment by beshoo** [comment]
And when I add a proxy with username and password 

```
[RANK]root:[/download/gowhatsap/go-whatsapp-master/examples/loginWithProxy]./login
panic: couldn't dial whatsapp web websocket: dial tcp: address mrqrc:redrgxxu@conn4.trs.ai:34871: too many colons in address

goroutine 1 [running]:

```

**Comment by beshoo** [comment]
Most problems form the timeout it is to short.
i update timeout to 50 sec - then it works
