### ISSUE TITLE
goroutine log, readPump errors and much more

### ISSUE THREAD

**Issue by beshoo** [Rhymen/go-whatsapp#346]
I have one runing session in background. 
Today while checking the log i found this long list of logs, and session is not responding i had to restart the api to get things back to normal, but what is this long logs and why it keep falling restoring the sessions? 

My "ReconnectForHandler" is

```
func ReconnectForHandler(wh *WaHandler) error {
        session := *(wh.Session)
        waSession, err := storage.GetSessionForID(*wh.SessionID)
        if err != nil {
                return err
        }
        wac, err := NewConn(waSession.ProxyURL)
        if err != nil {
                log.Errorf("ReconnectForHandler Connect failed%v", err)
                return err
        }
        wh.Wac.Disconnect()
        wac.SetClientName(longName, shortName , clientVersion)
        newSession, err := wac.RestoreWithSession(session)
        if err != nil {
                log.Errorf("ReconnectForHandler Restore failed%v", err)
                return err
        }
        wh.Wac.RemoveHandler(wh)
        wh.Wac = wac
        wh.Session = &newSession
        wac.AddHandler(wh)
        storage.UpdateSession(WASessionFromSession(*wh.SessionID, waSession.ProxyURL, wh.Hook, newSession))
        return nil
}

```

The error handler :

package whatsapp

```
import (
        "time"

        wa "github.com/Rhymen/go-whatsapp"
        log "github.com/sirupsen/logrus"
)

//
func (wh *WaHandler) HandleError(err error) {
        // log.Errorf("Handle Error %v", err)
        if e, ok := err.(*wa.ErrConnectionClosed); ok {
                if wh.Wac == nil {
                        log.Errorf("ErrConnectionClosed Wac is nill")
                        return
                }
                if wh.Wac.Info == nil {
                        log.Errorf("ErrConnectionClosed Wac Info is nill")
                        return
                }
                log.Errorf("%v ErrConnectionClosed %v", wh.Wac.Info.Wid, e)
                wh.logout()
                go wh.NotifyLogout(wh.Wac.Info.Wid)
                return
        }
        if e, ok := err.(*wa.ErrConnectionFailed); ok {
                log.Errorf("%v ErrConnectionFailed %v", wh.Wac.Info.Wid, e)
                go wh.NotifyConnectivity(false)
                wh.Signal <- PAUSE
                timer := time.NewTicker(30 * time.Second)
                for range timer.C {
                        log.Infof("%v Reconnecting... ", wh.Wac.Info.Wid)
                        err := ReconnectForHandler(wh)
                        if err == nil {
                                log.Infof("%v Reconnected ... sessionId %v", wh.Wac.Info.Wid, wh.SessionID)
                                go wh.NotifyConnectivity(true)
                                wh.Signal <- RESUME
                                timer.Stop()
                        }
                        if err != nil {
                                log.Errorf("%v Reconnecting Error %v", wh.Wac.Info.Wid, err)
                        }
                }
        }
}

```

Regard 

```
time="2020-04-29T08:35:06Z" level=error msg="14049190651@c.us ErrConnectionFailed connection to WhatsApp servers failed: websocket: close 1006 (abnormal closure)$
time="2020-04-29T08:35:06Z" level=info msg="Process Que Recieved Signal PAUSE"
time="2020-04-29T08:35:36Z" level=info msg="14049190651@c.us Reconnecting... "
time="2020-04-29T08:35:41Z" level=error msg="ReconnectForHandler Restore failedrestore session connection timed out"
time="2020-04-29T08:35:41Z" level=error msg="14049190651@c.us Reconnecting Error restore session connection timed out"

..........
LONG Reconnection Errors

time="2020-04-29T08:35:36Z" level=info msg="14049190651@c.us Reconnecting... "
time="2020-04-29T08:35:41Z" level=error msg="ReconnectForHandler Restore failedrestore session connection timed out"
time="2020-04-29T08:35:41Z" level=error msg="14049190651@c.us Reconnecting Error restore session connection timed out"
time="2020-04-29T08:36:06Z" level=info msg="14049190651@c.us Reconnecting... "
time="2020-04-29T08:36:11Z" level=error msg="ReconnectForHandler Restore failedrestore session connection timed out"
time="2020-04-29T08:36:11Z" level=error msg="14049190651@c.us Reconnecting Error restore session connection timed out"
time="2020-04-29T08:36:36Z" level=info msg="14049190651@c.us Reconnecting... "
time="2020-04-29T08:36:41Z" level=error msg="ReconnectForHandler Restore failedrestore session connection timed out"
time="2020-04-29T08:36:41Z" level=error msg="14049190651@c.us Reconnecting Error restore session connection timed out"

..........
fatal error: out of memory                                                      
                                                                                
runtime stack:                                                                  
runtime.throw(0x87ad4c3, 0xd)                                                   
        /usr/local/go/src/runtime/panic.go:774 +0x6a                            
runtime.largeAlloc(0x1900000, 0x8090101, 0xe71cd138)                            
        /usr/local/go/src/runtime/malloc.go:1140 +0x108                         
runtime.mallocgc.func1()

created by github.com/Rhymen/go-whatsapp.(*Conn).connect
/root/go/pkg/mod/github.com/!rhymen/go-whatsapp@v0.1.1-0.20200408093540-2f227c53b44f/conn.go:191 +0x2f9

goroutine 10915 [select]:
github.com/Rhymen/go-whatsapp.(*Conn).keepAlive(0xcfd6820, 0x4e20, 0xea60)
/root/go/pkg/mod/github.com/!rhymen/go-whatsapp@v0.1.1-0.20200408093540-2f227c53b44f/conn.go:240 +0x113
created by github.com/Rhymen/go-whatsapp.(*Conn).connect
/root/go/pkg/mod/github.com/!rhymen/go-whatsapp@v0.1.1-0.20200408093540-2f227c53b44f/conn.go:192 +0x32a

goroutine 10984 [select]:
github.com/Rhymen/go-whatsapp.(*Conn).readPump(0xd02c0a0)
/root/go/pkg/mod/github.com/!rhymen/go-whatsapp@v0.1.1-0.20200408093540-2f227c53b44f/read.go:33 +0x156
created by github.com/Rhymen/go-whatsapp.(*Conn).connect
/root/go/pkg/mod/github.com/!rhymen/go-whatsapp@v0.1.1-0.20200408093540-2f227c53b44f/conn.go:191 +0x2f9

goroutine 10985 [select]:
github.com/Rhymen/go-whatsapp.(*Conn).keepAlive(0xd02c0a0, 0x4e20, 0xea60)
/root/go/pkg/mod/github.com/!rhymen/go-whatsapp@v0.1.1-0.20200408093540-2f227c53b44f/conn.go:240 +0x113
created by github.com/Rhymen/go-whatsapp.(*Conn).connect
/root/go/pkg/mod/github.com/!rhymen/go-whatsapp@v0.1.1-0.20200408093540-2f227c53b44f/conn.go:192 +0x32a

goroutine 11705 [IO wait]:
internal/poll.runtime_pollWait(0xe728ac78, 0x72, 0xffffffff)
/usr/local/go/src/runtime/netpoll.go:184 +0x4b
internal/poll.(*pollDesc).wait(0xcdd56e4, 0x72, 0x1400, 0x1478, 0xffffffff)
/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x37
internal/poll.(*pollDesc).waitRead(...)
/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xcdd56d0, 0xd078a00, 0x1478, 0x1478, 0x0, 0x0, 0x0)
/usr/local/go/src/internal/poll/fd_unix.go:169 +0x16d
net.(*netFD).Read(0xcdd56d0, 0xd078a00, 0x1478, 0x1478, 0x0, 0xe74b5dbd, 0x1be)
/usr/local/go/src/net/fd_unix.go:202 +0x3f
net.(*conn).Read(0xcf10208, 0xd078a00, 0x1478, 0x1478, 0x0, 0x0, 0x0)
/usr/local/go/src/net/net.go:184 +0x56
crypto/tls.(*atLeastReader).Read(0xb00dbd0, 0xd078a00, 0x1478, 0x1478, 0x0, 0xb0165e4, 0x88d5b30)
/usr/local/go/src/crypto/tls/conn.go:780 +0x61
bytes.(*Buffer).ReadFrom(0xcf34d60, 0x88d4cd0, 0xb00dbd0, 0xd078a05, 0x8050309, 0x86fc5e0, 0x878dca0)
/usr/local/go/src/bytes/buffer.go:204 +0x95
crypto/tls.(*Conn).readFromUntil(0xcf34c00, 0x88d5b30, 0xcf10208, 0x5, 0xcf10208, 0x0)
/usr/local/go/src/crypto/tls/conn.go:802 +0xcb
crypto/tls.(*Conn).readRecordOrCCS(0xcf34c00, 0x0, 0x0, 0xbca0b958)
/usr/local/go/src/crypto/tls/conn.go:609 +0x114
crypto/tls.(*Conn).readRecord(...)
/usr/local/go/src/crypto/tls/conn.go:577
crypto/tls.(*Conn).Read(0xcf34c00, 0xe1ca4000, 0x1900000, 0x1900000, 0x0, 0x0, 0x0)
/usr/local/go/src/crypto/tls/conn.go:1255 +0x136
bufio.(*Reader).fill(0xb50f170)
/usr/local/go/src/bufio/bufio.go:100 +0xe9
bufio.(*Reader).Peek(0xb50f170, 0x2, 0x67ef24e5, 0xcb2683fe, 0x88ab34f5, 0x7aaddf5d, 0x2f87224c)
/usr/local/go/src/bufio/bufio.go:138 +0x41
github.com/gorilla/websocket.(*Conn).read(0xb14e180, 0x2, 0xe6d82eba, 0xe59db15e, 0x60ea18ea, 0x29654ec3, 0xdf415228)
/root/go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:370 +0x30
github.com/gorilla/websocket.(*Conn).advanceFrame(0xb14e180, 0x0, 0x0, 0xc06d05d5)
/root/go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:798 +0x60
github.com/gorilla/websocket.(*Conn).NextReader(0xb14e180, 0x2f027b70, 0xb1df87d2, 0x845359af, 0x16fa6840, 0x371d2191)
/root/go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:980 +0x89
github.com/Rhymen/go-whatsapp.(*Conn).readPump.func2(0xd02c0a0, 0xb6c6a20, 0xd0326c0, 0xd0326b8, 0xc34aa00)
/root/go/pkg/mod/github.com/!rhymen/go-whatsapp@v0.1.1-0.20200408093540-2f227c53b44f/read.go:30 +0x26
created by github.com/Rhymen/go-whatsapp.(*Conn).readPump
/root/go/pkg/mod/github.com/!rhymen/go-whatsapp@v0.1.1-0.20200408093540-2f227c53b44f/read.go:29 +0xee
```

**Comment by x00b** [comment]
Theres a fix for readPump error in pr #332  , but it wasnt merged and i'm not sure it will.

The session restoration error can be a lot of scenarios, phone offline for example. You should keep it restoring constantly.

**Comment by beshoo** [comment]
Regarding the "The out of memory, the issue is the https://github.com/Rhymen/go-whatsapp/issues/328"
I can not see a clear fix for it till now, Please did you manage to sort it out? and what should i do

**Comment by beshoo** [comment]
@x00b well I applied  wac.Disconnect(), but I don't like this method...
I can see the  #332 , merged just now. Gret :)
