### ISSUE TITLE
How can l handle WhatsApp servers failed: read.... 

### ISSUE THREAD

**Issue by beshoo** [Rhymen/go-whatsapp#358]
Sometimes l have this connection problem, 
 ```
msg="ErrConnectionFailed connection to WhatsApp servers failed: read tcp 107.6.183.138:51114->31.13.64.51:443: read: connection reset by peer"
panic: runtime error: invalid memory address or nil pointer dereference         [signal SIGSEGV: segmentation violation code=0x1 addr=0x1c pc=0x8603bc7]

goroutine 429 [running]:
whatsapp.(*WaHandler).NotifyConnectivity(0x9ce3700, 0x0)
/home/beshoo/go-wapi/wa/whatsapp/handler.go:143 +0x317
created by bitbucket.org/rockyOO7/wa-api/whatsapp.(*WaHandler).HandleError
/home/beshoo/go-wapi/wa/whatsapp/handle_error.go:42 +0xda

```
Which it triggered by line 42
go wh.NotifyConnectivity(false)

My error handler is 
```
package whatsapp

import (
"time"
//"fmt"
wa "github.com/Rhymen/go-whatsapp"
log "github.com/sirupsen/logrus"
)

//
func (wh *WaHandler) HandleError(err error) {
// log.Errorf("The Handle %v", wh.Session)
if e, ok := err.(*wa.ErrConnectionClosed); ok {
if wh.Wac == nil {
log.Errorf("ErrConnectionClosed Wac is nill")
return
}
if wh.Wac.Info == nil {
log.Errorf("ErrConnectionClosed Wac Info is nill")
return
}
log.Errorf("%v ErrConnectionClosed %v", wh.Wac.Info.Wid, e)
wh.logout()
go wh.NotifyLogout(wh.Wac.Info.Wid)
return
}
if e, ok := err.(*wa.ErrConnectionFailed); ok {

//log.Errorf("%v ErrConnectionFailed %v", wh.Wac.Info.Wid, e)
log.Errorf("ErrConnectionFailed %v", e)

go wh.NotifyConnectivity(false)
wh.Signal <- PAUSE
timer := time.NewTicker(30 * time.Second)
for range timer.C {
//log.Infof("%v Reconnecting... ", wh.Wac.Info.Wid)
                        log.Infof("Reconnecting... ")

err := ReconnectForHandler(wh)
if err == nil {
log.Infof("%v Reconnected ... sessionId %v", wh.Wac.Info.Wid, wh.SessionID)
go wh.NotifyConnectivity(true)
wh.Signal <- RESUME
timer.Stop()
}
if err != nil {
log.Errorf("%v Reconnecting Error %v", wh.Wac.Info.Wid, err)
}
}
}
}
```

What it the correct way to handle this type of network problems?

**Comment by Ased2235** [comment]
I'm getting same error too, but for me it's every 2 hours

**Comment by beshoo** [comment]
I add 

```
if wh == nil {
log.Errorf("ErrConnectionFailed Wac is nill")
return
}
```
before 
`go wh.NotifyConnectivity(false)
`
I am not sure , but i think at least we will not have a Os Panic, lets see what will happend

**Comment by beshoo** [comment]
Solved
