### ISSUE TITLE
Interface conversion: interface {} is nil in session!

### ISSUE THREAD

**Issue by beshoo** [Rhymen/go-whatsapp#488]
panic: interface conversion: interface {} is nil, not map[string]interface {}

```
goroutine 65 [running]:
github.com/Rhymen/go-whatsapp.newInfoFromReq(0xa2fa7c0, 0xa463400)
        /root/go/pkg/mod/github.com/!rhymen/go-whatsapp@v0.1.1-0.20200917103834-23c68e1d6342/session.go:64 +0xa10
github.com/Rhymen/go-whatsapp.(*Conn).Restore(0xa64a000, 0x0, 0x0)
        /root/go/pkg/mod/github.com/!rhymen/go-whatsapp@v0.1.1-0.20200917103834-23c68e1d6342/session.go:477 +0x106c
github.com/Rhymen/go-whatsapp.(*Conn).RestoreWithSession(0xa64a000, 0xa4ce2e0, 0x18, 0xa1f4180, 0x2c, 0xa418000, 0x52, 0xa1f4480, 0x20, 0x21, ...)
        /root/go/pkg/mod/github.com/!rhymen/go-whatsapp@v0.1.1-0.20200917103834-23c68e1d6342/session.go:339 +0xda

```

**Comment by beshoo** [comment]
Line in question 
https://github.com/Rhymen/go-whatsapp/blob/6e5488ac98dfc4b00fc7b4a73027b5002f89c4a6/session.go#L63

**Comment by zainul** [comment]
how to solve this issue ?
