### ISSUE TITLE
error decoding login connResp: json: cannot unmarshal array into Go value of type map[string]interface {}

### ISSUE THREAD

**Issue by castillofranciscodaniel** [Rhymen/go-whatsapp#633]
Hi! We were having a problem when the function Login() try to unmarshall the response from loginChan.  Unmarshall is expecting a []map[string]interface{} but it is receiving a map[string]interface{} 

`case r = <-loginChan:
	case <-time.After(wac.msgTimeout):
		return session, fmt.Errorf("login connection timed out")
	}

	var resp map[string]interface{}
	if err = json.Unmarshal([]byte(r), &resp); err != nil {
		return session, fmt.Errorf("error decoding login resp: %v\n", err)
	}`

Log from server: 
goroutine 11 [running]:
api-channel-whatsapp/pkg/messaging.login(0xc000198100, 0x1, 0x3)
        /go/src/app/pkg/messaging/whatsappImpl.go:553 +0x70e
api-channel-whatsapp/pkg/messaging.WhatsappSession()
        /go/src/app/pkg/messaging/whatsappImpl.go:395 +0x1c2

**Comment by fchattigo** [comment]
I thinks, that is not the place where unmarshall can not work. I was looking and i think the problem is in Restore(), in some 
 of the unmarshal

2021/11/03 17:05:38 [SUCCESS LOADIN CONFIG]
2021/11/03 17:05:39 [2 2121 6]
2021/11/03 17:05:39 [readSession][INIT]
2021/11/03 17:05:39 [DownloadSession][INIT]
2021/11/03 17:05:39 [DownloadSession][END]
2021/11/03 17:05:39 [readSession][END]
2021/11/03 17:05:39 [Login][ERROR] error decoding login connResp: json: cannot unmarshal array into Go value of type map[string]interface {}
panic: error decoding login connResp: json: cannot unmarshal array into Go value of type map[string]interface {}

**Comment by apariciojuan** [comment]
Try this.

`wac.SetClientVersion(3, 2123, 7)`

**Comment by manishswami** [comment]
Working..

WAC.SetClientVersion(2, 2142, 12)

**Comment by fchattigo** [comment]
Hi! thanks for answer me.Yes, it is working!

**Comment by gurlivleenkainth2000** [comment]
> Try this.
> 
> `wac.SetClientVersion(3, 2123, 7)`

Thank You
